version: '3.9'

services:
  web:
    container_name: desd-web-1
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: sh -c "sleep 15 && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    env_file:
      - .env


  mlaas:
    build:
      context: ./mlaas_service
    container_name: mlaas-service
    ports:
      - "9000:9000"
    volumes:
      - ./mlaas_service:/app
      - ./backend/media/ai_models:/app/models
    environment:
      - MODEL_PATH=models/active_model.pkl

  mysql:
    container_name: database-container-3
    image: mysql:latest
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend/static:/static
      - ./backend/media:/media
    depends_on:
      - web

volumes:
  mysql-data:

