# Generated by Django 4.2.21 on 2025-05-08 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingrecord',
            name='action',
            field=models.CharField(choices=[('prediction', 'Prediction')], max_length=50),
        ),
        migrations.AlterField(
            model_name='billingrecord',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
