FROM python:3.10-slim

# Set working directory inside the container
WORKDIR /code

# Install system-level dependencies for mysqlclient
RUN apt-get update && \
    apt-get install -y default-libmysqlclient-dev build-essential pkg-config && \
    apt-get clean

# Install Python dependencies
COPY ../requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Copy Django project files
COPY . .
