# Generated by Django 4.2.20 on 2025-05-06 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('model_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedmodel',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadedmodel',
            name='cluster_model_file',
            field=models.FileField(blank=True, null=True, upload_to='ai_models/'),
        ),
        migrations.AddField(
            model_name='uploadedmodel',
            name='preprocessor_file',
            field=models.FileField(blank=True, null=True, upload_to='ai_models/'),
        ),
        migrations.AddField(
            model_name='uploadedmodel',
            name='r2_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedmodel',
            name='rmse',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField()),
                ('output_data', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='model_manager.uploadedmodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
